[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["env -u NPM_CONFIG_PRODUCTION npm ci --include=dev"]

[phases.build]
cmds = ["tsc -p . --outDir dist && node ./tools/copy-services-proxy.mjs && echo daemon-built"]

[start]
cmd = "node dist/daemon/qflushd.js"
